// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rezobjbxywusdjphqfgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlem9iamJ4eXd1c2RqcGhxZmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjcwOTUsImV4cCI6MjA3MDE0MzA5NX0.8EoIonpcdSCiSsnr2LEEr5OOibPCH9WHkUn0QEDGYaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);